name: Secret Demoo
on:
  push:
    branches:
      - main
jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print secret
        run: echo "Secret is hidden"
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET }}
      - name: Use secret in script
        run: |
          echo "Using secret safely"
          echo "Length of secret: ${#SECRET_VALUE}"
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET }}
