name: Demo-CI
on: 
   push:
    branches: ["main"]
jobs:
 add-numbers:
   runs-on: ubuntu-latest
   steps: 
     
     - uses: actions/checkout@v4
     - name: addition
       run: echo 3+5=$((3+5))
     - name: subtraction
       run: echo 5-4=$((5-4))
      
      
     
 

